server:
  port: 8080

spring:
  servlet:
    # 파일 업로드
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
    encoding:
      charset: UTF-8
      force: true
  output:
    ansi:
      # 터미널에 컬러 출력
      enabled: ALWAYS
  web:
    resources:
      cache:
        cachecontrol:
          # 정적 리소스에 대한 캐시 사용 안함
          no-cache: true
  ai:
    openai:
      # API 키
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
  mandatory-file-encoding: UTF-8

logging:
  pattern:
    console: '[%clr(%-5level){green}] %clr(%logger.%M\(\)){cyan}: %msg%n'
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG # SimpleLoggerAdvisor
          tool: DEBUG # tool logging

naver:
  service:
    url: ${NAVER_SERVICE_URL}
    secretKey: ${NAVER_SERVICE_SECRET_KEY}